


### Register Student
POST http://localhost:5000/auth/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@gmail.com",
  "password": "john1234",
  "role": "STUDENT",
  "profileImageUrl": ""
}

### 3. Register  Admin
POST http://localhost:5000/auth/users
Content-Type: application/json

{
  "firstName": "Admin",
  "lastName": "User",
  "email": "admin@studyvault.com",
  "password": "admin1234",
  "role": "ADMIN",
  "profileImageUrl": ""
}

### Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "john.doe@gmail.com",
  "password": "john1234"
}
###Get My Profile 
GET http://localhost:5000/auth/me
Cookie: token=<eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMGQ3NmRhYmFhYzI4OTg3NGJlZGIwYyIsInJvbGUiOiJTVFVERU5UIiwiaWF0IjoxNzc5MjY4NjkxLCJleHAiOjE3ODE4NjA2OTF9.LMYOo2_jJSkheC-QiE6HEBV0X8AxbqGxT_X2H5w2HRM>

